
# GITHUB ISSUES REPORT FOR microsoft/pylance-release


Generated on 2022-07-14 using: stale=30, all=0


Only showing items that are new to report in past 1 day(s)


## FOR ISSUES THAT ARE MARKED AS BUGS:


### Issues in pylance-release that have no external responses since team response in 30+ days:


\* [2906](https://github.com/microsoft/pylance-release/issues/2906 "Extract method sometimes doesn't add a return statement"): team response was last response and no others in 30 days

---

## FOR ISSUES THAT ARE NOT MARKED AS BUGS:


### Issues in pylance-release that need a response from team:


\* [3032](https://github.com/microsoft/pylance-release/issues/3032 "[Bug] Function parentheses autocomplete does not recognize existing parentheses "): needs an initial team response (1 days old)

\* [3040](https://github.com/microsoft/pylance-release/issues/3040 "Support PEP 692 completions"): needs an initial team response (0 days old)

\* [3041](https://github.com/microsoft/pylance-release/issues/3041 "my vscode still cannot jump to definitions and references"): needs an initial team response (0 days old)

### Issues in pylance-release that have comments from OP after last team response:


\* [2991](https://github.com/microsoft/pylance-release/issues/2991 "Pylance can not auto import python modules"): OP responded 0 days ago but team last responded 7 days ago

\* [3029](https://github.com/microsoft/pylance-release/issues/3029 "pandas apply: Expression of type &quot;Series[Unknown]&quot; cannot be assigned to return type &quot;DataFrame&quot;"): OP responded 1 days ago but team last responded 1 days ago

\* [3030](https://github.com/microsoft/pylance-release/issues/3030 "Type of &quot;bpy&quot; is unknown"): OP responded 0 days ago but team last responded 1 days ago

### Issues in pylance-release that have comments from 3rd party after last team response:


\* [3012](https://github.com/microsoft/pylance-release/issues/3012 "Erroneous warnings &quot;constant not defined&quot; issued by Pylance"): 3rd party responded 0 days ago but team last responded 42 days ago

\* [3017](https://github.com/microsoft/pylance-release/issues/3017 "Import can not be resolved error in pylance jupyter notebook for importing .py file in same directory as notebook"): 3rd party responded 1 days ago but team last responded 2 days ago
